In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical
from numpy import array

In [3]:
#텍스트리뷰
docs = ["너무 재밌네요", "최고네요", "참 잘 만든 영화예요", "추천하고 싶은 영화입니다", "한번 더 보고싶네요", "글쎄요", "별로예요", "생각보다 지루해요", "연기가 어색해요", "재미없어요"]

In [4]:
#긍정리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [5]:
#토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고네요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루해요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [6]:
x=token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",x)


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [7]:
#패딩
padded_x = pad_sequences(x,4)
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [8]:
word_size=len(token.word_index)+1


In [9]:
model=Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              168       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 1s 1s/step - loss: 0.6896 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6874 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 14ms/step - loss: 0.6852 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6831 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 17ms/step - loss: 0.6809 - accuracy: 0.8000
Epoch 6/20
1/1 [==============================] - 0s 15ms/step - loss: 0.6787 - accuracy: 0.8000
Epoch 7/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6765 - accuracy: 0.8000
Epoch 8/20
1/1 [==============================] - 0s 16ms/step - loss: 0.6743 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 14ms/step - loss: 0.6721 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 20ms/step - loss: 0.6699 - accuracy: 0.9000
Epoch 11/20
1/1 [==============